---
# defaults file for openvpn-client
openvpn_client_dev: tun
openvpn_dst_config: /etc/openvpn/client.conf
openvpn_client_cert: "{{ lookup('file', 'files/client/client.crt') }}"
openvpn_client_key: "{{ lookup('file', 'files/client/client.key') }}"
openvpn_ca: "{{ lookup('file', 'files/client/ca.crt') }}"
openvpn_tls: "{{ lookup('file', 'files/client/tls.key') }}"