---
# handlers file for openvpn-client
- name: start_openvpn
  become: yes
  service: name="openvpn@{{ openvpn_dst_config | basename | replace('.conf', '') }}.service" state=restarted enabled=yes
  listen: "restart openvpn services"


