ansible_ssh_user: user
openvpn_client_dev: tun
openvpn_client_remote: 192.168.1.25
openvpn_client_remote_port: 1194
openvpn_client_remote_protocol: tcp
openvpn_dst_config: /etc/openvpn/client.conf
openvpn_client_cert: "{{ lookup('file', 'files/client/client.crt') }}"
openvpn_client_key: "{{ lookup('file', 'files/client/client.key') }}"
openvpn_ca: "{{ lookup('file', 'files/client/ca.crt') }}"
openvpn_tls: "{{ lookup('file', 'files/client/tls.key') }}"