---
# tasks file for install-docker
    - name: Install packages
      become: yes
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    - name: Add an Apt signing key, uses whichever key is at the URL
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: add repository for docker
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install Dopcker packages
      become: yes
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Download docker-compose
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ ansible_userspace_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: '0775'