- hosts: qq_host
  become: yes
  tasks:
    - name: First install packades
      apt:
        name: "{{item}}"
      with_items:
        - aptitude
        - vim
        - mc
        - unzip
        - wget
      tags:
        - base

    - name: Add an Apt signing key, uses whichever key is at the URL
      become: yes
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
      tags:
        - virtualbox

# Added virtualbox_repo
    - name: add_repository
      become: yes
      apt_repository:
        repo: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
        state: present
        filename: virtualbox
      tags:
        - virtualbox

#Install virtualbox
    - name: install virtualbox
      become: yes
      apt:
        name: "{{item}}"
      with_items:
        - virtualbox-6.0
      tags:
        - virtualbox

    - name: Install wps-office
      vars:
        version: 8372
      apt:
        deb: "http://kdl.cc.ksosoft.com/wps-community/download/{{version}}/wps-office_11.1.0.{{version}}_amd64.deb"
      tags:
        - office
#- name: create user
#  hosts: all
#  roles:
#  - { role: adduser }