---
- name: add users with default password (pass)
  become: yes
  user:
    name: '{{ item.name }}'
#    password: "$6$VKqjcNgs4TtBG$qB4rZVnSME1ZVCxd/bWrX2uwKz5VQIYPZA5CEtfuDyIz/BQennnDgyD5vWrai2QpmJU/pqTY2vXqMixinju76."
    shell: /bin/bash
    createhome: yes
    groups: '{{ item.groups }}'
  with_items: '{{ adduser.users }}'
  when: item.change

- name: set authorized key
  become: yes
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', 'ssh/{{ item.name }}.pub') }}"
    path: /home/{{ item.name }}/.ssh/authorized_keys
    state: present
  with_items: "{{ adduser.users }}"
  when: item.change
- name: "Add user item.name to sudo"
  become: yes
  lineinfile:
    path: "/etc/sudoers.d/{{item.sudo.file}}"
    line: '{{item.name}} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
  validate: 'visudo -cf %s'
  with_items: "{{ adduser.users }}"
  when: item.sudo is defined
#- name: set change password before first login
#  command: chage -d 0 {{ item.name }}
#  with_items: '{{ adduser.users }}'
#  when: item.change

- name: remove user
  become: yes
  user:
    name: '{{ item }}'
    state: absent
    remove: yes
  with_items: '{{ rmuser.users }}'
  when: rmuser is defined

- name: lock user
  become: yes
  user:
    name: '{{ item }}'
    password_lock: yes
  with_items: '{{ lock.users }}'
  when: lock is defined
...