galaxy_info:
  author: Igor Stetsyuk
  description: create users
  company: ZEO
  license: BSD
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  galaxy_tags:
    - users
    - adduser
    - rmuser
dependencies: []
