---
# tasks file for install-gitlab
- name: 'Download script froom offsite'
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/{{item}}
    dest: /tmp/{{item}}
    mode: 775
  with_items: "{{script}}"

- name: 'Start script'
  become: yes
  command: /tmp/{{item}}
  with_items: "{{script}}"

- name: 'Install packages for gitlab'
  become: yes
  apt:
    name: "{{item}}"
  with_items: "{{packages}}"

- name: 'Configure gitlab'
  become: yes
  command: 'gitlab-ctl reconfigure'

