- name: Install packages
  become: yes
  apt:
    name: openvpn=2.3.10-1ubuntu2
    state: fixed

- name: write client config
  become: yes
  template: src="{{ item }}.j2" dest="/{{ item }}" owner=root group=root  mode='0400'
  notify: restart openvpn services
  with_items:
    - "{{ openvpn_dst_config }}"


-


