adduser:
  users:
    - name: user
      groups: ''
      change: true
      sudo:
        change: true
        line:
          - "user ALL=(ALL) NOPASSWD: ALL"

gitlab_runner_registration_token: 'DXw9zDnQWDzYM_ESEzJm'
gitlab_runner_coordinator_url: "http://192.168.1.15/"
gitlab_runner_concurrent: 1
gitlab_runner_runners:
  - name: 'Example Docker GitLab Runner'
    executor: docker
    docker_image: 'debian'
    tags:
      - node
      - ruby
      - mysql
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    extra_configs:
      runners.docker:
        memory: 512m
        allowed_images: ["ruby:*", "python:*", "php:*"]
      runners.docker.sysctls:
        net.ipv4.ip_forward: "1"
